Repository Jagroop2001/Pages-A-Book-Shop-Website, pull requests merged in 2024-03, with the labels that each got.

#17 Adding contact details like email, location of the company, and adding details in the ABOUT and SERVICES section.
  about.html
  images/envelope-regular.svg
  index.html
  services.html
Labels: WOC, Medium

#16 Implementing Icons Instead of Pictures in Social Media Options
  images/Facebook.png
  images/LinkedIn.png
  images/Twitter.png
  index.css
  index.html
Labels: WOC, Easy

#21 Added Signup Page
  formData.json
  images/library.jpg
  index.css
  scripts/sign-up.js
  sign-up.html
  styles/sign-up.css
Labels: WOC, Hard

#23 Fixing all the broken links and adding new links for other pages.
  about.html
  index.html
  services.html
  sign-up.html
Labels: WOC, Medium

#25 Booking Page Initialisation
  .vscode/settings.json
  booking.html
  index.css
  index.html
  script.js
Labels: WOC, Hard

#24 adding animation to forefront
  Scripts/anim1.js
  Scripts/anim2.js
  images/Book.png
  images/background.avif
  index.css
  index.html
Labels: WOC, Medium

#27 Integration of Trending Books Showcase section with Auto Horizontal Scroll
  Scripts/slider.js
  index.css
  index.html
  styles/slider.css
Labels: WOC, Easy

#31 feat: added login page
  Scripts/login.js
  images/loginimg.avif
  login.html
  scripts/sign-up.js
  styles/login.css
Labels: WOC, Hard

#30 Adding a Search bar on the top in the navbar and minor bug fixes.
  about.html
  booking.html
  checkout.html
  index.html
  services.html
Labels: WOC, Medium

#33 Interconnecting Login and Sign-up pages, adding the links in navbar and some minor bug fixes.
  about.html
  booking.html
  checkout.html
  index.html
  login.html
  services.html
  sign-up.html
Labels: WOC, Hard
